<?php
/**
 * Removes Native Link Health plugin data.
 *
 * Destructive cleanup is OPT-IN (since 1.5.6). Without the opt-in only the
 * plugin's own volatile scratch state is cleared — never the user's data.
 * Dropping the tables also destroys nlh_health_history, the ~90-day snapshot
 * trail the Pro plugin's trend report reads, so a plain "deactivate and delete
 * core" used to silently wipe Pro's charts even with Pro still installed.
 *
 * Mirrors the Pro plugin's nlhp_remove_all_on_uninstall opt-in.
 *
 * @package NativeLinkHealth
 */

if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	exit;
}

global $wpdb;

/*
 * Always-safe cleanup: transient caches, backoff counters and per-post scan
 * timestamps. These are derived scratch state — regenerated by the next scan —
 * so removing them leaves nothing the user would miss, and leaving them behind
 * would litter the options table on a genuine uninstall.
 */
delete_option( '_transient_nlh_suggestions' );
delete_option( '_transient_timeout_nlh_suggestions' );
delete_option( '_transient_nlh_seo_audit_results' );
delete_option( '_transient_timeout_nlh_seo_audit_results' );
delete_option( '_transient_nlh_manual_scan_active' );
delete_option( '_transient_timeout_nlh_manual_scan_active' );

delete_post_meta_by_key( '_nlh_last_scan' );

$transient_ok_prefix             = $wpdb->esc_like( '_transient_nlh_ok_' ) . '%';
$transient_ok_timeout_prefix     = $wpdb->esc_like( '_transient_timeout_nlh_ok_' ) . '%';
$transient_retry_prefix          = $wpdb->esc_like( '_transient_nlh_retry_' ) . '%';
$transient_retry_timeout_prefix  = $wpdb->esc_like( '_transient_timeout_nlh_retry_' ) . '%';
$transient_fail_prefix           = $wpdb->esc_like( '_transient_nlh_fail_' ) . '%';
$transient_fail_timeout_prefix   = $wpdb->esc_like( '_transient_timeout_nlh_fail_' ) . '%';
$transient_broken_counts_prefix  = $wpdb->esc_like( '_transient_nlh_broken_counts_' ) . '%';
$transient_broken_counts_timeout = $wpdb->esc_like( '_transient_timeout_nlh_broken_counts_' ) . '%';
$last_ok_option_prefix           = $wpdb->esc_like( 'nlh_last_ok_' ) . '%';
$last_soft_option_prefix         = $wpdb->esc_like( 'nlh_last_soft_' ) . '%';

$wpdb->query(
	$wpdb->prepare(
		"DELETE FROM {$wpdb->options}
		WHERE option_name LIKE %s
		OR option_name LIKE %s
		OR option_name LIKE %s
		OR option_name LIKE %s
		OR option_name LIKE %s
		OR option_name LIKE %s
		OR option_name LIKE %s
		OR option_name LIKE %s
		OR option_name LIKE %s
		OR option_name LIKE %s",
		$transient_ok_prefix,
		$transient_ok_timeout_prefix,
		$transient_retry_prefix,
		$transient_retry_timeout_prefix,
		$transient_fail_prefix,
		$transient_fail_timeout_prefix,
		$transient_broken_counts_prefix,
		$transient_broken_counts_timeout,
		$last_ok_option_prefix,
		$last_soft_option_prefix
	)
);

/*
 * Everything below is the user's own data. It goes only when the site owner
 * explicitly asked for it in Settings > Link Health > Data & Uninstall.
 */
if ( ! (bool) get_option( 'nlh_remove_all_on_uninstall', false ) ) {
	return;
}

$table                = $wpdb->prefix . 'nlh_link_errors';
$events_table         = $wpdb->prefix . 'nlh_link_events';
$correction_log_table = $wpdb->prefix . 'nlh_correction_log';

$wpdb->query( "DROP TABLE IF EXISTS {$table}" );
$wpdb->query( "DROP TABLE IF EXISTS {$events_table}" );
$wpdb->query( "DROP TABLE IF EXISTS {$correction_log_table}" );

$link_map_table    = $wpdb->prefix . 'nlh_link_map';
$link_scores_table = $wpdb->prefix . 'nlh_link_scores';

$wpdb->query( "DROP TABLE IF EXISTS {$link_map_table}" );
$wpdb->query( "DROP TABLE IF EXISTS {$link_scores_table}" );

delete_option( 'nlh_db_version' );
delete_option( 'nlh_juice_dirty' );
delete_option( 'nlh_juice_computed_at' );
delete_option( 'nlh_health_history' );
delete_option( 'nlh_ignored_urls' );
delete_option( 'nlh_scan_batch_size' );
delete_option( 'nlh_scan_scope' );
delete_option( 'nlh_comment_scan_last_id' );
delete_option( 'nlh_scan_metrics' );
delete_option( 'nlh_auto_rules' );
delete_option( 'nlh_show_welcome' );
delete_option( 'nlh_remove_all_on_uninstall' );
